meta_product_name: "REfood"
meta_title: "REfood - Save money and fight against food waste"
meta_description: "An application that holds bundled information about food close to their expiration date in your area."
meta_image: "refood-logo.png"
